.PHONY: clean All

All:
	@echo "----------Building project:[ assignmentTools - Debug ]----------"
	@cd "assignmentTools" && "$(MAKE)" -f  "assignmentTools.mk"
clean:
	@echo "----------Cleaning project:[ assignmentTools - Debug ]----------"
	@cd "assignmentTools" && "$(MAKE)" -f  "assignmentTools.mk" clean
