.PHONY: clean All

All:
	@echo "----------Building project:[ usingPointers - Debug ]----------"
	@cd "usingPointers" && "$(MAKE)" -f  "usingPointers.mk"
clean:
	@echo "----------Cleaning project:[ usingPointers - Debug ]----------"
	@cd "usingPointers" && "$(MAKE)" -f  "usingPointers.mk" clean
