.PHONY: clean All

All:
	@echo "----------Building project:[ assignmentSolution - Debug ]----------"
	@cd "assignmentSolution" && "$(MAKE)" -f  "assignmentSolution.mk"
clean:
	@echo "----------Cleaning project:[ assignmentSolution - Debug ]----------"
	@cd "assignmentSolution" && "$(MAKE)" -f  "assignmentSolution.mk" clean
